#Login information for epic fight patron server. Do not change these values manually
access_token = ""
refresh_token = ""
#Allowed Values: NULL, DISCORD, PATREON
provider = "NULL"

[ingame]
	#Range: 1 ~ 10
	long_press_count = 2
	#Range: 0 ~ 30
	max_hit_projectiles = 30
	camera_auto_switch = true
	blood_effects = true
	show_epicfight_attributes = true
	first_person_model = true
	enable_pov_action = true
	enable_cosmetics = true
	combat_preferred_items = ["efn:co_tachi", "minecraft:wooden_sword", "wom:evil_tachi", "epicfight:iron_longsword", "wom:herrscher", "wom:golden_greataxe", "aether:flaming_sword", "wom:solar", "irons_spellbooks:misery", "epicfight:diamond_greatsword", "efn:nf_shortsword_2", "epicfight:wooden_tachi", "efn:hf_murasama", "irons_spellbooks:keeper_flamberge", "wom:hollow_longsword", "alexsmobs:skelewag_sword", "epicfight:diamond_dagger", "minecraft:netherite_sword", "efn:nf_shortsword", "epicfight:golden_greatsword", "wom:antitheus", "minecraft:stone_axe", "wom:agony", "epicfight:iron_tachi", "efn:meen_spear", "cataclysm:gauntlet_of_guard", "efn:ruinsgreatsword", "efn:yamato_dmc", "aquamirae:terrible_sword", "irons_spellbooks:hellrazor", "epicfight:golden_spear", "efn:excalibur", "lost_aether_content:phoenix_sword", "wom:ruine", "irons_spellbooks:claymore", "minecraft:diamond_sword", "invincible:custom_skill_demo", "epicfightx:yoto", "epicfightx:eternal_night_scythe", "cataclysm:meat_shredder", "tcrcore:dual_bokken", "bosses_of_mass_destruction:earthdive_spear", "efn:crescent_moon", "aether:valkyrie_lance", "wom:orbit", "minecraft:crossbow", "aether:candy_cane_sword", "epicfight:iron_dagger", "irons_spellbooks:legionnaire_flamberge", "cataclysm:soul_render", "invincible:debug", "cataclysm:coral_spear", "aether:holystone_sword", "mowziesmobs:wrought_axe", "aether:vampire_blade", "aether:holy_sword", "epicfight:wooden_greatsword", "minecraft:diamond_axe", "wom:napoleon", "efn:sword_of_pioneer", "irons_spellbooks:boreal_blade", "create:cardboard_sword", "wom:iron_greataxe", "epicfight:netherite_spear", "cataclysm:tidal_claws", "efn:arc_tachi", "aether:gravitite_sword", "aquamirae:maze_rose", "invincible:custom_combo_demo", "wom:stone_staff", "minecraft:netherite_axe", "efn:kusabimaru", "aquamirae:coral_lance", "efn:yamato_dmc_in_sheath", "epicfight:diamond_spear", "efn:yamato_dmc4", "tcrcore:the_incinerator_soul", "epicfight:netherite_tachi", "cataclysm:black_steel_sword", "minecraft:stone_sword", "wom:ender_blaster", "aether:lightning_sword", "alexsmobs:tendon_whip", "mowziesmobs:blowgun", "epicfight:diamond_tachi", "efn:crimson_moon", "aether:pig_slayer", "super_golem:golem_heart", "irons_spellbooks:amethyst_rapier", "epicfight:netherite_dagger", "epicfight:iron_spear", "wom:netherite_greataxe", "epicfight:glove", "cataclysm:cursed_bow", "epicfightx:great_tachi", "minecraft:bow", "epicfight:uchigatana", "cataclysm:final_fractal", "aether:phoenix_bow", "wom:iron_staff", "fromtheshadows:devil_splitter", "wom:moonless", "aether:zanite_sword", "artifacts:vampiric_glove", "epicfight:diamond_longsword", "sword_soaring:vatansever", "minecraft:trident", "efn:fire_exsiliumgladius", "dodosmobs:amalgam_claws", "irons_spellbooks:decrepit_scythe", "epicfight:stone_spear", "aquamirae:fin_cutter", "wom:jabberwocky", "efn:thornwheel", "minecraft:iron_sword", "efn:nf_claw", "aquamirae:whisper_of_the_abyss", "efn:broadblade", "epicfight:stone_longsword", "epicfightx:efx_uchigatana", "efn:yamato_dmc4_in_sheath", "irons_spellbooks:spellbreaker", "wom:satsujin", "cataclysm:the_incinerator", "p1nero_bow:oblivionis", "aether:skyroot_sword", "epicfight:wooden_spear", "cataclysm:ancient_spear", "aquamirae:divider", "artifacts:power_glove", "aquamirae:dagger_of_greed", "cataclysm:the_annihilator", "alexsmobs:falconry_glove", "epicfight:stone_tachi", "p1nero_bow:mortis", "cataclysm:zweiender", "fromtheshadows:thirst_for_blood", "efn:air_tachi", "cataclysm:ceraunus", "cataclysm:infernal_forge", "fromtheshadows:crystallized_dagger", "aquamirae:poisoned_blade", "cataclysm:khopesh", "wom:nova", "cataclysm:athame", "epicfight:netherite_greatsword", "wom:wooden_staff", "wom:diamond_greataxe", "cataclysm:wrath_of_the_desert", "epicfight:bokken", "epicfight:golden_dagger", "wom:netherite_staff", "wom:blackstar", "irons_spellbooks:twilight_gale", "aether:hammer_of_kingbdogz", "aquamirae:sweet_lance", "aquamirae:poisoned_chakra", "efn:flag_bearer", "minecraft:iron_axe", "epicfight:stone_dagger", "minecraft:wooden_axe", "epicfight:wooden_dagger", "aquamirae:remnants_saber", "cataclysm:astrape", "efn:nf_dual_sword", "minecraft:golden_axe", "minecraft:golden_sword", "epicfight:iron_greatsword", "wom:diamond_staff", "cataclysm:coral_bardiche", "wom:golden_staff", "mowziesmobs:naga_fang_dagger", "epicfight:netherite_longsword", "irons_spellbooks:magehunter", "epicfight:stone_greatsword", "epicfight:wooden_longsword", "epicfight:golden_longsword", "epicfight:golden_tachi", "wom:tormented_mind", "irons_spellbooks:autoloader_crossbow", "efn:exsiliumgladius"]
	show_target_indicator = true
	#Allowed Values: NONE, HURT, TARGET, TARGET_AND_HURT
	health_bar_show_option = "HURT"
	use_compute_shader = true
	enable_target_entity_guide = false
	#Allowed Values: NONE, CROSSHAIR, HIGHLIGHT, CROSSHAIR_AND_HIGHLIGHT
	mine_block_guide_option = "NONE"
	#Allowed Values: NONE, INTERACTION, ITEM_USE, INTERACTION_AND_ITEMUSE
	key_conflict_resolve_scope = "INTERACTION"
	enable_player_vanilla_model = true
	#Allowed Values: ADAPTIVE, SWITCH_MODE
	preference_work = "ADAPTIVE"
	mining_preferred_items = ["minecraft:air"]
	#Range: 0.0 ~ 1.0
	target_outline_color = 0.0
	#Defines how the camera toggles perspectives.
	#
	#    1. Vanilla (Default)
	#       Uses Minecraft's default behavior.
	#       Cycles through all available perspectives.
	#
	#    2. Skip Third-Person Front Perspective
	#       Skips only the front view when toggling.
	#       Other perspectives remain available.
	#
	#Allowed Values: VANILLA, SKIP_THIRD_PERSON_FRONT
	camera_perspective_toggle_mode = "SKIP_THIRD_PERSON_FRONT"

	[ingame.ui]
		stamina_bar_x = 120
		stamina_bar_y = 10
		#Allowed Values: LEFT, RIGHT, CENTER
		stamina_bar_x_base = "RIGHT"
		#Allowed Values: TOP, BOTTOM, CENTER
		stamina_bar_y_base = "BOTTOM"
		weapon_innate_x = 42
		weapon_innate_y = 48
		#Allowed Values: LEFT, RIGHT, CENTER
		weapon_innate_x_base = "RIGHT"
		#Allowed Values: TOP, BOTTOM, CENTER
		weapon_innate_y_base = "BOTTOM"
		passives_x = 70
		passives_y = 36
		#Allowed Values: LEFT, RIGHT, CENTER
		passives_x_base = "RIGHT"
		#Allowed Values: TOP, BOTTOM, CENTER
		passives_y_base = "BOTTOM"
		#Allowed Values: HORIZONTAL, VERTICAL
		passives_align_direction = "HORIZONTAL"
		charging_bar_x = -119
		charging_bar_y = 60
		#Allowed Values: LEFT, RIGHT, CENTER
		charging_bar_x_base = "CENTER"
		#Allowed Values: TOP, BOTTOM, CENTER
		charging_bar_y_base = "CENTER"

	[ingame.camera]
		#Allowed Values: ALWAYS_BACK, WHEN_AIMING, ALWAYS
		camera_mode = "ALWAYS"
		#Range: -10 ~ 10
		horizontal_location = -4
		#Range: -2 ~ 5
		vertical_location = 0
		#Range: 6 ~ 10
		zoom = 7
		#Range: 5 ~ 25
		lock_on_range = 20
		lock_on_quick_shift = true

